export default [
  {
    name: "YYShopItemTop",
    text: "店铺详情头部",
    icon: "",
    data: {
      backgroundColor: "#fff",
      color: "#000",
      id: "1",
      icon: "http://file.yuansheng.com/static/memo/logos/19151604.png",
      dilivery_start_price: "20",
      dilivery_price: "1",
      distanceTime: 30,
      notice: "关闭店铺了",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "5px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTabBar",
    text: "标签栏",
    icon: "",
    data: {
      defaultValue: "0",
      tabList: [
        { title: "商品", value: "0", url: "/pages/goods/index" },
        { title: "评价", value: "1", url: "/pages/comment/index" },
        { title: "商家", value: "2", url: "/pages/shop/detail" },
      ],
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "2px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTabGoods",
    text: "分类商品",
    icom: "",
    data: {
      tabDirection: "vertical",
      flexDirection: "row",
      tabUrl: "/classifies",
      tabs: {
        store: "classifyStore",
        tabUrl: "/classifies",
        take: 10,
        skip: 0,
        current: 0,
        tabDirection: "vertical",
        tabList: [
          { id: "1", name: "水果", value: "0", title: "水果" },
          { id: "2", name: "肉禽蛋", value: "1", title: "肉禽蛋" },
          { id: "3", name: "蔬菜", value: "2", title: "蔬菜" },
        ],
      },
      goodUrl: "/goods",
      goods: {
        goodUrl: "/goods",
        skip: 0,
        take: 10,
        hasBorder: true,
        borderRadius: "0px",
        backgroundColor: "#fff",
        type: "imageLeft",
        inline: false,
        columnNum: 1,
        imageMode: "scaleToFill",
        imageWidth: "100px",
        imageHeight: "100px",
        itemPadding: "5px",
        itemMargin: "5px",
        textAlign: "left",
        cartImage: "",
        data: [
          {
            id: "xxx1",
            icon: "https://file.yuanshengyoupin.com/files/hb10.png",
            name: "领取中心",
            price_min: 11,
            original_price: 12,
          },
          {
            id: "xxx2",
            icon: "https://file.yuanshengyoupin.com/files/hb10.png",
            name: "找折扣",
            url: "https://yuanshengyoupin.com",
            price_min: 11,
            original_price: 12,
          },
          {
            id: "xxx3",
            icon: "https://file.yuanshengyoupin.com/files/hb10.png",
            name: "领会员",
            price_min: 11,
            original_price: 0,
          },
          {
            id: "xxx4",
            icon: "https://file.yuanshengyoupin.com/files/hb10.png",
            name: "新品首发",
            price_min: 0,
            original_price: 0,
          },
        ],
      },
    },
    children: [],
  },
];
