export default [
  {
    name: "YYShopItemTop",
    text: "店铺详情头部",
    icon: "",
    data: {
      backgroundColor: "#fff",
      color: "#000",
      id: "1",
      icon: "http://file.yuansheng.com/static/memo/logos/19151604.png",
      dilivery_start_price: "20",
      dilivery_price: "1",
      distanceTime: 30,
      notice: "关闭店铺了",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "5px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTabBar",
    text: "标签栏",
    icon: "",
    data: {
      defaultValue: "2",
      tabList: [
        { title: "商品", value: "0", url: "/pages/goods/index" },
        { title: "评论", value: "1", url: "/pages/comment/index" },
        { title: "店铺", value: "2", url: "/pages/shop/detail" },
      ],
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "",
      fontSize: "16px",
      height: "4px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "http://file.yuansheng.com/static/memo/logos/19151604.png",
      title: "营业资质",
      fontSize: "14px",
      padding: "10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYImageList",
    text: "图片列表",
    icon: "",
    data: {
      flexDirection: "row",
      data: [
        {
          src: "https://file.yuanshengyoupin.com/files/hb10.png",
          mode: "widthFix",
          width: "auto",
          height: "auto",
          borderRadius: "0px",
        },
        {
          src: "https://file.yuanshengyoupin.com/files/hb10.png",
          mode: "widthFix",
          width: "auto",
          height: "auto",
          borderRadius: "0px",
        },
        {
          src: "https://file.yuanshengyoupin.com/files/hb10.png",
          mode: "widthFix",
          width: "auto",
          height: "auto",
          borderRadius: "0px",
        },
      ],
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "5px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYSubTitle",
    text: "标题&副标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "http://file.yuansheng.com/static/memo/logos/19151604.png",
      title: "配送服务",
      subTitle: "由商家提供配送",
      more: "",
      url: "",
      fontSize: "14px",
      padding: "5px 10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYList",
    text: "列表",
    icon: "https://file.yuanshengyoupin.com/files/List.png",
    data: {
      hasBorder: false,
      data: [
        {
          title: "电话：18507152527",
          arrow: "right",
          thumb:
            "https://img12.360buyimg.com/jdphoto/s72x72_jfs/t6160/14/2008729947/2754/7d512a86/595c3aeeNa89ddf71.png",
        },
        {
          title: "地址：武汉大学校内",
          arrow: "right",
          thumb:
            "https://img12.360buyimg.com/jdphoto/s72x72_jfs/t6160/14/2008729947/2754/7d512a86/595c3aeeNa89ddf71.png",
        },
        {
          title: "营业时间：10:00 - 21:00",
          arrow: "right",
          thumb:
            "https://img12.360buyimg.com/jdphoto/s72x72_jfs/t6160/14/2008729947/2754/7d512a86/595c3aeeNa89ddf71.png",
        },
      ],
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "5px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYList",
    text: "列表",
    icon: "https://file.yuanshengyoupin.com/files/List.png",
    data: {
      hasBorder: false,
      data: [
        {
          title: "进店可领五元代金券",
          arrow: "",
          thumb:
            "https://img12.360buyimg.com/jdphoto/s72x72_jfs/t6160/14/2008729947/2754/7d512a86/595c3aeeNa89ddf71.png",
        },
        {
          title: "满28元减2元，满58元减6元",
          arrow: "",
          thumb:
            "https://img12.360buyimg.com/jdphoto/s72x72_jfs/t6160/14/2008729947/2754/7d512a86/595c3aeeNa89ddf71.png",
        },
      ],
    },
    children: [],
  },
  {
    name: "YYButton",
    text: "按钮",
    icon: "https://file.yuanshengyoupin.com/files/button.png",
    data: {
      title: "举报商家",
      margin: "0px",
      borderRadius: "0px",
      size: "default",
      type: "primary",
      plain: true,
      disabled: false,
      loading: false,
    },
    children: [],
  },
];
