export default [
  {
    name: "YYSwiper",
    text: "轮播图",
    icon: "https://file.yuanshengyoupin.com/files/banner.png",
    data: {
      vertical: false,
      items: [
        {
          url: "#",
          image:
            "https://file.yuanshengyoupin.com/files/%E9%BE%99%E8%A5%BF%E7%94%B5%E5%AD%90%E5%8E%823.jpg",
          imageStyle: {},
        },
        {
          url: "#",
          image:
            "https://file.yuanshengyoupin.com/files/%E9%BE%99%E8%A5%BF%E7%94%B5%E5%AD%904.jpg",
          imageStyle: {},
        },
      ],
    },
    children: [],
  },
  {
    name: "YYCartGood",
    text: "单个商品",
    icon: "",
    data: {
      image: "",
      value: "龙西电子厂",
      desc: "工厂主要生产照明设备，耳机等，空调车间，组装包装岗位，工作简单轻松，全部手工活！不用体检，普通工衣！",
      url: "https://yuanshengyoupin.com",
      price: " 17-19 元/小时",
      originalPrice: "",
      borderRadius: "0px",
      imageMode: "scaleToFill",
      imageWidth: "100px",
      imageHeight: "100%",
      itemPadding: "5px",
      itemMargin: "0px",
      items: [{ url: "#" }, { url: "#" }],
      vertical: false,
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "夜班补贴",
      fontSize: "14px",
      padding: "10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "夜班补助12元/晚。" },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "招聘福利",
      fontSize: "14px",
      padding: "10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "大部分坐班长白班。" },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: {
      content:
        "食宿情况：空调宿舍，宿舍在厂区，包吃包住，纯包吃3餐，宿舍水电均摊。",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "招聘要求",
      fontSize: "14px",
      padding: "10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "男女不限：17-42岁" },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: {
      content:
        "需本人身份证有磁，无案底，小纹身可以，四大少数民族免！高风险地区一律不收，深圳市内14天不查核酸，外省来深48小时核酸！！！",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "温馨提示",
      fontSize: "14px",
      padding: "10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: {
      content:
        "自带身份证复印件和一寸照片各2张，行程码和粤康码打印一张，厂内严禁吸烟（除吸烟区），每月底发放上个月工资！",
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "下午三点之前到厂~" },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "5px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYImage",
    text: "图片",
    icon: "",
    data: {
      src: "https://file.yuanshengyoupin.com/files/%E9%BE%99%E8%A5%BF%E7%94%B5%E5%AD%901.png",
      mode: "widthFix",
      width: "100%",
      height: "100px",
      borderRadius: "0px",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "50px",
      backgroundColor: "#fff",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYButton",
    text: "按钮",
    icon: "https://file.yuanshengyoupin.com/files/button.png",
    data: {
      title: "立即报名",
      url: "/pages/job/apply?jobId=1&jobName=龙西电子厂",
      margin: "0px",
      borderRadius: "0px",
      size: "default",
      type: "primary",
      backgroundColor: "#fff",
      color: "#000",
      plain: false,
      disabled: false,
      loading: false,
    },
    children: [],
  },
];
