export default [
  {
    name: "YYSwiper",
    text: "轮播图",
    icon: "https://file.yuanshengyoupin.com/files/banner.png",
    data: {
      vertical: false,
      items: [
        {
          url: "#",
          image:
            "https://file.yuanshengyoupin.com/files/%E5%B8%83%E5%90%89%E7%94%B5%E5%AD%90%E5%8E%821.png",
          imageStyle: {},
        },
        {
          url: "#",
          image:
            "https://file.yuanshengyoupin.com/files/%E5%B8%83%E5%90%89%E7%94%B5%E5%AD%90%E5%8E%824.png",
          imageStyle: {},
        },
      ],
    },
    children: [],
  },
  {
    name: "YYCartGood",
    text: "单个商品",
    icon: "",
    data: {
      image: "",
      value: "布吉电子厂",
      desc: "环境优美，空调车间，生产液晶电视机等产品，组装包装测试等岗位，普通工衣",
      url: "#",
      price: " 18-20 元/小时",
      originalPrice: "",
      borderRadius: "0px",
      imageMode: "scaleToFill",
      imageWidth: "100px",
      imageHeight: "100%",
      itemPadding: "5px",
      itemMargin: "0px",
      items: [{ url: "#" }, { url: "#" }],
      vertical: false,
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYContact",
    text: "联系",
    icon: "https://file.yuanshengyoupin.com/files/shop-banner.png",
    data: {
      logo: "https://file.yuanshengyoupin.com/files/%E5%A5%B3%E5%AE%A2%E6%9C%8D.png",
      notice: "梦企传媒 - 正能量招聘咨询",
      phone: "13257681336",
      wechat: "LW981198",
      telImage:
        "https://file.yuanshengyoupin.com/files/209%E7%94%B5%E8%AF%9D-%E7%BA%BF%E6%80%A7%E5%9C%86%E6%A1%86.png",
      wxImage: "https://file.yuanshengyoupin.com/files/%E5%BE%AE%E4%BF%A1.png",
      margin: "10px",
      borderRadius: "10px",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "夜班补贴",
      fontSize: "14px",
      padding: "10px",
      onClick: "",
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "夜班补贴20元/晚" },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "招聘要求",
      fontSize: "14px",
      padding: "10px",
      onClick: "",
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "男女不限  16-42岁" },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "查行程无*号即可，不查核酸" },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "面试岗位 A",
      fontSize: "14px",
      padding: "10px",
      onClick: "",
    },
    children: [],
  },
  {
    name: "YYCartGood",
    text: "单个商品",
    icon: "",
    data: {
      image: "",
      value: "TV基板站班/坐班两班倒（流水线）",
      desc: "透镜站班两班倒（独立岗位）",
      url: "#",
      price: " 19元/小时+1元餐补",
      originalPrice: "",
      borderRadius: "0px",
      imageMode: "scaleToFill",
      imageWidth: "100px",
      imageHeight: "100%",
      itemPadding: "5px",
      itemMargin: "0px",
      items: [{ url: "#" }, { url: "#" }],
      vertical: false,
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "面试岗位 B",
      fontSize: "14px",
      padding: "10px",
      onClick: "",
    },
    children: [],
  },
  {
    name: "YYCartGood",
    text: "单个商品",
    icon: "",
    data: {
      image: "",
      value: "通信坐班两班倒",
      desc: "",
      url: "#",
      price: " 18元/小时+1元餐补",
      originalPrice: "",
      borderRadius: "0px",
      imageMode: "scaleToFill",
      imageWidth: "100px",
      imageHeight: "100%",
      itemPadding: "5px",
      itemMargin: "0px",
      items: [{ url: "#" }, { url: "#" }],
      vertical: false,
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "食宿情况",
      fontSize: "14px",
      padding: "10px",
      onClick: "",
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: {
      content: "住宿为电梯公寓式宿舍、有空调、独立卫生间、WiFi、有热水器 ",
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "7人间，伙食好，自由选餐。每周五可借支300元！" },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "温馨提示",
      fontSize: "14px",
      padding: "10px",
      onClick: "",
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: {
      content:
        "面试时自带身份证复印件和照片各2张，在职每月18号之前发放上月工资。",
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "下午三点之前到厂~" },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "5px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYImage",
    text: "图片",
    icon: "",
    data: {
      src: "https://file.yuanshengyoupin.com/files/%E5%B8%83%E5%90%89%E7%94%B5%E5%AD%90%E5%8E%821.png",
      mode: "widthFix",
      width: "100%",
      height: "240px",
      borderRadius: "10px",
    },
    children: [],
  },
  {
    name: "YYImage",
    text: "图片",
    icon: "",
    data: {
      src: "https://file.yuanshengyoupin.com/files/%E5%B8%83%E5%90%89%E7%94%B5%E5%AD%90%E5%8E%822.png",
      mode: "widthFix",
      width: "100%",
      height: "240px",
      borderRadius: "10px",
    },
    children: [],
  },
  {
    name: "YYImage",
    text: "图片",
    icon: "",
    data: {
      src: "https://file.yuanshengyoupin.com/files/%E5%B8%83%E5%90%89%E7%94%B5%E5%AD%90%E5%8E%823.png",
      mode: "widthFix",
      width: "100%",
      height: "240px",
      borderRadius: "10px",
    },
    children: [],
  },
  {
    name: "YYImage",
    text: "图片",
    icon: "",
    data: {
      src: "https://file.yuanshengyoupin.com/files/%E5%B8%83%E5%90%89%E7%94%B5%E5%AD%90%E5%8E%824.png",
      mode: "widthFix",
      width: "100%",
      height: "240px",
      borderRadius: "10px",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "50px",
      backgroundColor: "#fff",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYButton",
    text: "按钮",
    icon: "https://file.yuanshengyoupin.com/files/button.png",
    data: {
      title: "立即报名",
      url: "/pages/job/apply?jobId=2&jobName=布吉电子厂",
      margin: "0px",
      borderRadius: "0px",
      size: "default",
      type: "primary",
      backgroundColor: "#fff",
      color: "#000",
      plain: false,
      disabled: false,
      loading: false,
      height: "50px",
    },
    children: [],
  },
];
