export default [
  {
    name: "YYSwiper",
    text: "轮播图",
    icon: "https://file.yuanshengyoupin.com/files/banner.png",
    data: {
      vertical: false,
      items: [
        {
          url: "#",
          image:
            "https://file.yuanshengyoupin.com/files/%E8%91%B5%E6%B6%8C%E5%90%88%E5%8A%9B%E6%B3%B0%E7%94%B5%E5%AD%90%E5%8E%821.png",
          imageStyle: {},
        },
        {
          url: "#",
          image:
            "https://file.yuanshengyoupin.com/files/%E8%91%B5%E6%B6%8C%E5%90%88%E5%8A%9B%E6%B3%B0%E7%94%B5%E5%AD%90%E5%8E%822.png",
          imageStyle: {},
        },
        {
          url: "#",
          image:
            "https://file.yuanshengyoupin.com/files/%E8%91%B5%E6%B6%8C%E5%90%88%E5%8A%9B%E6%B3%B0%E7%94%B5%E5%AD%90%E5%8E%823.png",
          imageStyle: {},
        },
        {
          url: "#",
          image:
            "https://file.yuanshengyoupin.com/files/%E8%91%B5%E6%B6%8C%E5%90%88%E5%8A%9B%E6%B3%B0%E7%94%B5%E5%AD%90%E5%8E%824.png",
          imageStyle: {},
        },
      ],
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYCartGood",
    text: "单个商品",
    icon: "",
    data: {
      image: "",
      value: "葵涌合力泰电子厂",
      desc: "工厂环境优美，交通便利。主要生产手机，触摸屏，摄像头等电子元件。两班倒，半个月倒班一次，恒温空调车间、空调宿舍，做事较轻松，好留人!",
      url: "#",
      price: " 5000-6000 元/月",
      originalPrice: "",
      borderRadius: "0px",
      imageMode: "scaleToFill",
      imageWidth: "100px",
      imageHeight: "100%",
      itemPadding: "5px",
      itemMargin: "0px",
      items: [{ url: "#" }, { url: "#" }],
      vertical: false,
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "食宿环境",
      fontSize: "14px",
      padding: "10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: {
      content: "包住空调宿舍24小时热水，洗衣机，衣柜，餐补220元/月，吃超自付！",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "招聘要求",
      fontSize: "14px",
      padding: "10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "男女不限：17-42岁" },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "坐班两班倒 普通工衣/无尘服随机分配" },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "面试要求",
      fontSize: "14px",
      padding: "10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "身份证复印件1张照片2张" },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "企业地址",
      fontSize: "14px",
      padding: "10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "深圳龙岗" },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "5px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYImage",
    text: "图片",
    icon: "",
    data: {
      src: "https://file.yuanshengyoupin.com/files/%E8%91%B5%E6%B6%8C%E5%90%88%E5%8A%9B%E6%B3%B0%E7%94%B5%E5%AD%90%E5%8E%821.png",
      mode: "widthFix",
      width: "100%",
      height: "300px",
      borderRadius: "0px",
    },
    children: [],
  },
  {
    name: "YYImage",
    text: "图片",
    icon: "",
    data: {
      src: "https://file.yuanshengyoupin.com/files/%E8%91%B5%E6%B6%8C%E5%90%88%E5%8A%9B%E6%B3%B0%E7%94%B5%E5%AD%90%E5%8E%822.png",
      mode: "widthFix",
      width: "100%",
      height: "200px",
      borderRadius: "0px",
    },
    children: [],
  },
  {
    name: "YYImage",
    text: "图片",
    icon: "",
    data: {
      src: "https://file.yuanshengyoupin.com/files/%E8%91%B5%E6%B6%8C%E5%90%88%E5%8A%9B%E6%B3%B0%E7%94%B5%E5%AD%90%E5%8E%823.png",
      mode: "widthFix",
      width: "100%",
      height: "260px",
      borderRadius: "0px",
    },
    children: [],
  },
  {
    name: "YYImage",
    text: "图片",
    icon: "",
    data: {
      src: "https://file.yuanshengyoupin.com/files/%E8%91%B5%E6%B6%8C%E5%90%88%E5%8A%9B%E6%B3%B0%E7%94%B5%E5%AD%90%E5%8E%824.png",
      mode: "widthFix",
      width: "100%",
      height: "280px",
      borderRadius: "0px",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "50px",
      backgroundColor: "#fff",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYButton",
    text: "按钮",
    icon: "https://file.yuanshengyoupin.com/files/button.png",
    data: {
      title: "立即报名",
      url: "/pages/job/apply?jobId=3&jobName=葵涌合力泰电子厂",
      margin: "0px",
      borderRadius: "0px",
      size: "default",
      type: "primary",
      backgroundColor: "#fff",
      color: "#000",
      plain: false,
      disabled: false,
      loading: false,
      height: "50px",
    },
    children: [],
  },
];
