export default [
  {
    name: "YYSwiper",
    text: "轮播图",
    icon: "https://file.yuanshengyoupin.com/files/banner.png",
    data: {
      vertical: false,
      items: [
        {
          url: "#",
          image:
            "https://file.yuanshengyoupin.com/files/%E5%B9%B3%E6%B9%96%E9%87%91%E8%BF%9B%E7%94%B5%E5%AD%90%E5%8E%821.png",
          imageStyle: {},
        },
        {
          url: "#",
          image:
            "https://file.yuanshengyoupin.com/files/%E5%B9%B3%E6%B9%96%E9%87%91%E8%BF%9B%E7%94%B5%E5%AD%90%E5%8E%822.png",
          imageStyle: {},
        },
      ],
    },
    children: [],
  },
  {
    name: "YYCartGood",
    text: "单个商品",
    icon: "",
    data: {
      image: "",
      value: "平湖金进电子厂",
      desc: "主要生产饮料售卖机中的汽水泵、电动牙刷，家用电器等。普通工衣，车间可带手机。",
      url: "#",
      price: " 5500-6500 元/月",
      originalPrice: "",
      borderRadius: "0px",
      imageMode: "scaleToFill",
      imageWidth: "100px",
      imageHeight: "100%",
      itemPadding: "5px",
      itemMargin: "0px",
      items: [{ url: "#" }, { url: "#" }],
      vertical: false,
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "招聘福利",
      fontSize: "14px",
      padding: "10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "包吃住三餐，吃住基本都在一起，宿舍走路5分钟之内。" },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: {
      content: "宿舍环境好，24小时热水，每个床位有独立柜子，部分空调部分风扇。",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "招聘要求",
      fontSize: "14px",
      padding: "10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "男女不限，18-45岁" },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "一针疫苗以上" },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "基本坐班两班倒  个别长白班（削披风）" },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "面试要求",
      fontSize: "14px",
      padding: "10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: {
      content:
        "纹身穿短袖看不见可以，四大少数民族免，不能穿拖鞋，短裤，会填表认字，身份证有效期大于3个月，身体健康无色盲！统一体检费用自理或有正规医院的体检表和健康证三个月内有效期也可以。",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "企业地址",
      fontSize: "14px",
      padding: "10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "深圳龙岗" },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "5px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYImage",
    text: "图片",
    icon: "",
    data: {
      src: "https://file.yuanshengyoupin.com/files/%E5%B9%B3%E6%B9%96%E9%87%91%E8%BF%9B%E7%94%B5%E5%AD%90%E5%8E%821.png",
      mode: "widthFix",
      width: "100%",
      height: "200px",
      borderRadius: "0px",
    },
    children: [],
  },
  {
    name: "YYImage",
    text: "图片",
    icon: "",
    data: {
      src: "https://file.yuanshengyoupin.com/files/%E5%B9%B3%E6%B9%96%E9%87%91%E8%BF%9B%E7%94%B5%E5%AD%90%E5%8E%822.png",
      mode: "widthFix",
      width: "100%",
      height: "200px",
      borderRadius: "0px",
    },
    children: [],
  },
  {
    name: "YYImage",
    text: "图片",
    icon: "",
    data: {
      src: "https://file.yuanshengyoupin.com/files/%E5%B9%B3%E6%B9%96%E9%87%91%E8%BF%9B%E7%94%B5%E5%AD%90%E5%8E%824.png",
      mode: "widthFix",
      width: "100%",
      height: "200px",
      borderRadius: "0px",
    },
    children: [],
  },
  {
    name: "YYImage",
    text: "图片",
    icon: "",
    data: {
      src: "https://file.yuanshengyoupin.com/files/%E5%B9%B3%E6%B9%96%E9%87%91%E8%BF%9B%E7%94%B5%E5%AD%90%E5%8E%823.png",
      mode: "widthFix",
      width: "100%",
      height: "200px",
      borderRadius: "0px",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "50px",
      backgroundColor: "#fff",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYButton",
    text: "按钮",
    icon: "https://file.yuanshengyoupin.com/files/button.png",
    data: {
      title: "立即报名",
      url: "/pages/job/apply?jobId=4&jobName=平湖金进电子厂",
      margin: "0px",
      borderRadius: "0px",
      size: "default",
      type: "primary",
      backgroundColor: "#fff",
      color: "#000",
      plain: false,
      disabled: false,
      loading: false,
    },
    children: [],
  },
];
