export default [
  {
    name: "YYSwiper",
    text: "轮播图",
    icon: "https://file.yuanshengyoupin.com/files/banner.png",
    data: {
      vertical: false,
      items: [
        {
          url: "#",
          image: "https://file.yuanshengyoupin.com/files/龙西贝克电子1.png",
          imageStyle: {},
        },
      ],
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYCartGood",
    text: "单个商品",
    icon: "",
    data: {
      image: "",
      value: "龙西贝克电子",
      desc: "工厂主要生产照明设备，耳机等，空调车间，组装包装岗位，工作简单轻松，全部手工活！不用体检，普通工衣！",
      url: "https://yuanshengyoupin.com",
      price: " 4500-5500 元/月",
      originalPrice: "",
      borderRadius: "0px",
      imageMode: "scaleToFill",
      imageWidth: "100px",
      imageHeight: "100%",
      itemPadding: "5px",
      itemMargin: "0px",
      items: [{ url: "#" }, { url: "#" }],
      vertical: false,
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "食宿环境",
      fontSize: "14px",
      padding: "10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: {
      content: "空调宿舍，宿舍在厂区，包吃包住，纯包吃3餐，宿舍水电均摊",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "招聘要求",
      fontSize: "14px",
      padding: "10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "男女不限：17-42岁" },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "需本人身份证有磁，无案底，小纹身可以" },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "企业地址",
      fontSize: "14px",
      padding: "10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "深圳龙岗" },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "5px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYImage",
    text: "图片",
    icon: "",
    data: {
      src: "https://file.yuanshengyoupin.com/files/12.jpg",
      mode: "widthFix",
      width: "100%",
      height: "360px",
      borderRadius: "0px",
    },
    children: [],
  },
  {
    name: "YYImage",
    text: "图片",
    icon: "",
    data: {
      src: "https://file.yuanshengyoupin.com/files/11.jpg",
      mode: "widthFix",
      width: "100%",
      height: "360px",
      borderRadius: "0px",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "50px",
      backgroundColor: "#fff",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYButton",
    text: "按钮",
    icon: "https://file.yuanshengyoupin.com/files/button.png",
    data: {
      title: "立即报名",
      url: "/pages/job/apply?jobId=5&jobName=龙西贝克电子",
      margin: "0px",
      borderRadius: "0px",
      size: "default",
      type: "primary",
      backgroundColor: "#fff",
      color: "#000",
      plain: false,
      disabled: false,
      loading: false,
    },
    children: [],
  },
];
