export default [
  {
    name: "YYSwiper",
    text: "轮播图",
    icon: "https://file.yuanshengyoupin.com/files/banner.png",
    data: {
      vertical: false,
      items: [
        {
          url: "#",
          image:
            "https://file.yuanshengyoupin.com/files/%E5%9D%AA%E5%9C%B0%E8%A3%95%E5%90%8C%E5%8C%85%E8%A3%85%E5%8E%821.png",
          imageStyle: {},
        },
        {
          url: "#",
          image:
            "https://file.yuanshengyoupin.com/files/%E5%9D%AA%E5%9C%B0%E8%A3%95%E5%90%8C%E5%8C%85%E8%A3%85%E5%8E%822.png",
          imageStyle: {},
        },
      ],
    },
    children: [],
  },
  {
    name: "YYCartGood",
    text: "单个商品",
    icon: "",
    data: {
      image: "",
      value: "坪地裕同包装厂",
      desc: "裕同集团上市公司，坪地厂区1000多人（深南电路厂边），主要生产产品：彩盒、礼品盒、说明书 、纸箱及其它印刷包装配套等高档产品， 集团环境非常好，花园式全新厂房、宿舍，生活、娱乐等设施齐全完善。普通工衣，两班倒有站有坐！",
      url: "#",
      price: " 5500-6500 元/月",
      originalPrice: "",
      borderRadius: "0px",
      imageMode: "scaleToFill",
      imageWidth: "100px",
      imageHeight: "100%",
      itemPadding: "5px",
      itemMargin: "0px",
      items: [{ url: "#" }, { url: "#" }],
      vertical: false,
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "食宿环境",
      fontSize: "14px",
      padding: "10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "餐补300元，入职直接充饭卡里，" },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: {
      content:
        "公司内有饭堂、超市、图书馆、健身房、电视机、乒乓球室、篮球场等，",
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: {
      content:
        "电梯公寓空调宿舍、无线网络、24小时供热水、洗衣机、带卫生间宿舍，衣柜。",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "招聘要求",
      fontSize: "14px",
      padding: "10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "需本人身份证有磁，无案底，小纹身可以， " },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "男女不限：18-42岁" },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "行程码风险地区不收，需要疫苗1针以上" },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "面试信息",
      fontSize: "14px",
      padding: "10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: {
      content:
        "面试不严，提供本人有磁真实有效二代身份证，人脸识别打卡，身体健康、需要体检，四大少数民族已满，带行李、口罩、穿拖鞋者不予面试。",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "企业地址",
      fontSize: "14px",
      padding: "10px",
      onClick: function onClick() {},
    },
    children: [],
  },
  {
    name: "YYP",
    text: "P",
    icon: "",
    data: { content: "深圳龙岗" },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "5px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYImage",
    text: "图片",
    icon: "",
    data: {
      src: "https://file.yuanshengyoupin.com/files/%E5%9D%AA%E5%9C%B0%E8%A3%95%E5%90%8C%E5%8C%85%E8%A3%85%E5%8E%821.png",
      mode: "widthFix",
      width: "100%",
      height: "230px",
      borderRadius: "0px",
    },
    children: [],
  },
  {
    name: "YYImage",
    text: "图片",
    icon: "",
    data: {
      src: "https://file.yuanshengyoupin.com/files/%E5%9D%AA%E5%9C%B0%E8%A3%95%E5%90%8C%E5%8C%85%E8%A3%85%E5%8E%822.png",
      mode: "widthFix",
      width: "100%",
      height: "230px",
      borderRadius: "0px",
    },
    children: [],
  },
  {
    name: "YYImage",
    text: "图片",
    icon: "",
    data: {
      src: "https://file.yuanshengyoupin.com/files/%E5%9D%AA%E5%9C%B0%E8%A3%95%E5%90%8C%E5%8C%85%E8%A3%85%E5%8E%823.png",
      mode: "widthFix",
      width: "100%",
      height: "500px",
      borderRadius: "0px",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "50px",
      backgroundColor: "#fff",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYButton",
    text: "按钮",
    icon: "https://file.yuanshengyoupin.com/files/button.png",
    data: {
      title: "立即报名",
      url: "/pages/job/apply?jobId=6&jobName=坪地裕同包装厂",
      margin: "0px",
      borderRadius: "0px",
      size: "default",
      type: "primary",
      backgroundColor: "#fff",
      color: "#000",
      plain: false,
      disabled: false,
      loading: false,
    },
    children: [],
  },
];
