export default [
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYTitle",
    text: "标题",
    icon: "https://file.yuanshengyoupin.com/files/titleSub.png",
    data: {
      icon: "",
      title: "立即报名",
      fontSize: "16px",
      padding: "10px",
      onClick: "",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "5px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYInput",
    text: "输入框",
    icon: "",
    data: {
      name: "jobId",
      label: "职位 ID :",
      store: "careerApplyStore",
      placeholder: "",
      flexDirection: "column",
      disabled: true,
      onInput: "",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "1px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYInput",
    text: "输入框",
    icon: "",
    data: {
      name: "jobName",
      label: "职位名称 :",
      store: "careerApplyStore",
      placeholder: "",
      flexDirection: "column",
      disabled: true,
      onInput: "",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "1px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYInput",
    text: "输入框",
    icon: "",
    data: {
      name: "name",
      label: "姓名 ：",
      store: "careerApplyStore",
      placeholder: "请输入姓名",
      flexDirection: "column",
      disabled: false,
      onInput: "",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "1px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYInput",
    text: "输入框",
    icon: "",
    data: {
      name: "phone",
      label: "手机号 ：",
      store: "careerApplyStore",
      placeholder: "请输入手机号",
      flexDirection: "column",
      disabled: false,
      onInput: "",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#eee",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "50px",
      backgroundColor: "#fff",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYSubmit",
    text: "提交",
    icon: "https://file.yuanshengyoupin.com/files/button.png",
    data: {
      title: "提交",
      url: "/pages/index/index",
      store: "careerApplyStore",
      margin: "0px",
      fixBottom: false,
      borderRadius: "0px",
      size: "default",
      type: "primary",
      backgroundColor: "#fff",
      color: "#000",
      plain: false,
      disabled: false,
      loading: false,
    },
    children: [],
  },
];
