export default [
  {
    name: "YYSwiper",
    text: "轮播图",
    icon: "https://file.yuanshengyoupin.com/files/banner.png",
    data: {
      vertical: false,
      items: [
        {
          url: "/pages/job/detail/1",
          image:
            "https://file.yuanshengyoupin.com/files/%E9%BE%99%E8%A5%BF%E7%94%B5%E5%AD%901.png",
          imageStyle: {},
        },
      ],
    },
    children: [],
  },
  {
    name: "YYSpaceline",
    text: "占位线",
    icon: "",
    data: {
      content: "",
      color: "#ed3f14",
      fontSize: "16px",
      height: "1px",
      backgroundColor: "#ddd",
      textAlign: "center",
    },
    children: [],
  },
  {
    name: "YYCartGood",
    text: "单个商品",
    icon: "",
    data: {
      image:
        "https://file.yuanshengyoupin.com/files/%E9%BE%99%E8%A5%BF%E7%94%B5%E5%AD%90%E5%8E%823.jpg",
      value: "龙西电子厂",
      desc: "工厂主要生产照明设备，耳机等，空调车间，组装包装岗位，工作简单轻松，全部手工活！不用体检，普通工衣！",
      url: "/pages/job/detail/1",
      price: " 17-19 元/小时",
      originalPrice: "",
      borderRadius: "0px",
      imageMode: "aspectFill",
      imageWidth: "100px",
      imageHeight: "100%",
      itemPadding: "5px",
      itemMargin: "0px",
    },
    children: [],
  },
  {
    name: "YYCartGood",
    text: "单个商品",
    icon: "",
    data: {
      image:
        "https://file.yuanshengyoupin.com/files/%E5%B8%83%E5%90%89%E7%94%B5%E5%AD%90%E5%8E%822.png",
      value: "布吉兆驰电子",
      desc: "环境优美，空调车间，生产液晶电视机等产品，组装包装测试等岗位，普通工衣",
      url: "/pages/job/detail/2",
      price: " 18-20 元/小时",
      originalPrice: "",
      borderRadius: "0px",
      imageMode: "aspectFill",
      imageWidth: "100px",
      imageHeight: "100%",
      itemPadding: "5px",
      itemMargin: "0px",
    },
    children: [],
  },
  {
    name: "YYCartGood",
    text: "单个商品",
    icon: "",
    data: {
      image:
        "https://file.yuanshengyoupin.com/files/%E8%91%B5%E6%B6%8C%E5%90%88%E5%8A%9B%E6%B3%B0%E7%94%B5%E5%AD%90%E5%8E%822.png",
      value: "葵涌合力泰电子厂",
      desc: "工厂环境优美，交通便利。主要生产手机，触摸屏，摄像头等电子元件。",
      url: "/pages/job/detail/3",
      price: " 5000-6000 元/月",
      originalPrice: "",
      borderRadius: "0px",
      imageMode: "aspectFill",
      imageWidth: "100px",
      imageHeight: "100%",
      itemPadding: "5px",
      itemMargin: "0px",
    },
    children: [],
  },
  {
    name: "YYCartGood",
    text: "单个商品",
    icon: "",
    data: {
      image:
        "https://file.yuanshengyoupin.com/files/%E5%B9%B3%E6%B9%96%E9%87%91%E8%BF%9B%E7%94%B5%E5%AD%90%E5%8E%824.png",
      value: "平湖金进电子厂",
      desc: "主要生产饮料售卖机中的汽水泵、电动牙刷，家用电器等。普通工衣，车间可带手机。",
      url: "/pages/job/detail/4",
      price: " 5500-6500 元/月",
      originalPrice: "",
      borderRadius: "0px",
      imageMode: "aspectFill",
      imageWidth: "100px",
      imageHeight: "100%",
      itemPadding: "5px",
      itemMargin: "0px",
    },
    children: [],
  },
  {
    name: "YYCartGood",
    text: "单个商品",
    icon: "",
    data: {
      image: "https://file.yuanshengyoupin.com/files/11.jpg",
      value: "龙西贝克电子",
      desc: "工厂主要生产照明设备，耳机等，空调车间，组装包装岗位，工作简单轻松，全部手工活！不用体检，普通工衣",
      url: "/pages/job/detail/5",
      price: " 4500-5500 元/月",
      originalPrice: "",
      borderRadius: "0px",
      imageMode: "aspectFill",
      imageWidth: "100px",
      imageHeight: "100%",
      itemPadding: "5px",
      itemMargin: "0px",
    },
    children: [],
  },
  {
    name: "YYCartGood",
    text: "单个商品",
    icon: "",
    data: {
      image:
        "https://file.yuanshengyoupin.com/files/%E5%9D%AA%E5%9C%B0%E8%A3%95%E5%90%8C%E5%8C%85%E8%A3%85%E5%8E%823.png",
      value: "坪地裕同包装厂",
      desc: "裕同集团上市公司，坪地厂区1000多人（深南电路厂边），主要生产产品：彩盒、礼品盒、说明书 、纸箱及其它印刷包装配套等高档产品。",
      url: "/pages/job/detail/6",
      price: " 5500-6500 元/月",
      originalPrice: "",
      borderRadius: "0px",
      imageMode: "aspectFill",
      imageWidth: "100px",
      imageHeight: "100%",
      itemPadding: "5px",
      itemMargin: "0px",
    },
    children: [],
  },
];
